version: '3.8'
services:
  movies:
    image: keerthigunda/paymoviess:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: keerthigunda/paytrainn:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: keerthigunda/paydthh:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: keerthigunda/payrechargee:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
